fix: Path doesn't implement Display
Can't use the variables directly in the `format!`, need to call
`.display()` explicitly.

```
error[E0277]: `std::path::Path` doesn't implement `std::fmt::Display`
  --> crates/stellar-registry-macro/src/contract.rs:90:88
```

But in `contract_client.rs` we want to show the full path, not just the
`wasm.name()`. Since `Versioned` implements `Display`, we can shorten
this to put `wasm` in the `format!`.